name: DB12 testing

on: [push, pull_request]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    if: github.event_name != 'push'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit
      run: pre-commit run --all-files --show-diff-on-failure

  pytest:
    runs-on: ubuntu-20.04
    if: github.event_name != 'push' || github.repository == 'DIRACGrid/db12'

    strategy:
      matrix:
        python:
          - 2.7.18
          - 3.6.15
          - 3.9.17
          - 3.11.4

    container: python:${{ matrix.python }}-slim
    steps:
    - uses: actions/checkout@v4
    - name: Installing dependencies
      run: |
        python -m pip install pytest mock
        pip install -e .
    - name: Run pytest
      run: pytest

  pylint:
    runs-on: ubuntu-20.04
    if: github.event_name != 'push' || github.repository == 'DIRACGrid/db12'
    timeout-minutes: 10

    strategy:
      matrix:
        python:
          - 2.7.18
          - 3.6.15
          - 3.9.17

    container: python:${{ matrix.python }}-slim
    steps:
    - uses: actions/checkout@v4
    - name: Installing dependencies
      run: |
        python -m pip install pylint pytest mock
    - name: Run pylint
      run: pylint -E src/db12 tests
